import { createContext, useContext, useState, ReactNode, useCallback } from "react";

export type Language = "en" | "hu" | "la" | "el" | "zh";

export const LANGUAGE_LABELS: Record<Language, string> = {
  en: "English",
  hu: "Magyar",
  la: "Latina",
  el: "Ελληνικά",
  zh: "中文",
};

export const LANGUAGE_FLAGS: Record<Language, string> = {
  en: "🇬🇧",
  hu: "🇭🇺",
  la: "🏛️",
  el: "🇬🇷",
  zh: "🇨🇳",
};

// Translation keys
const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navbar
    "nav.home": "Home",
    "nav.leaderboard": "Leaderboard",
    "nav.practice": "Practice",
    "nav.shop": "Shop",
    "nav.friends": "Friends",
    "nav.lobbies": "Lobbies",
    "nav.community": "Community",
    "nav.profile": "Profile",
    "nav.login": "Login",
    "nav.settings": "Settings",
    // Hero
    "hero.title": "Logic",
    "hero.title2": "Guesser",
    "hero.subtitle": "Test your brainpower with daily puzzles, battle friends, and climb the global leaderboard.",
    "hero.daily": "Start Daily Challenge",
    "hero.practice": "Practice Mode",
    "hero.badge": "New Daily Challenge Available",
    "hero.statPuzzles": "Puzzles Solved",
    "hero.statPlayers": "Active Players",
    "hero.statDaily": "Daily Challenges",
    // Profile
    "profile.level": "Level",
    "profile.streak": "Streak",
    "profile.solved": "Solved",
    "profile.credits": "Credits",
    "profile.logout": "Log Out",
    "profile.editBio": "Edit bio",
    "profile.addBio": "Add bio",
    "profile.noBio": "No bio yet",
    "profile.editName": "Edit name",
    "profile.upgradePro": "Upgrade to Pro",
    "profile.goPro": "Go Pro",
    "profile.changeName": "Change Username",
    "profile.saveName": "Save",
    // Settings
    "settings.title": "SETTINGS",
    "settings.notifications": "Notifications",
    "settings.notificationsDesc": "Enable in-app notifications",
    "settings.battleInvites": "Battle Invites",
    "settings.battleInvitesDesc": "Get notified when someone invites you to battle",
    "settings.creditRewards": "Credit Rewards",
    "settings.creditRewardsDesc": "Get notified when you earn credits",
    "settings.friendRequests": "Friend Requests",
    "settings.friendRequestsDesc": "Get notified about new friend requests",
    "settings.sound": "Sound Effects",
    "settings.soundDesc": "Play sounds for game events",
    "settings.email": "Email Notifications",
    "settings.emailDesc": "Receive email alerts for important events",
    "settings.save": "Save Settings",
    "settings.changePassword": "Change Password",
    "settings.changePasswordDesc": "Update your account password",
    "settings.newPassword": "New password (min 6 chars)",
    "settings.confirmPassword": "Confirm new password",
    "settings.updatePassword": "Update Password",
    "settings.updating": "Updating...",
    "settings.loggedInAs": "Logged in as:",
    "settings.language": "Language",
    "settings.languageDesc": "Choose your preferred language",
    // Login
    "login.title": "Welcome Back",
    "login.subtitle": "Sign in to continue your puzzle journey",
    "login.email": "Email",
    "login.password": "Password",
    "login.signIn": "Sign In",
    "login.signingIn": "Signing in...",
    "login.forgotPassword": "Forgot password?",
    "login.noAccount": "Don't have an account yet?",
    "login.createAccount": "Create an Account",
    "login.orSignUp": "Maybe you don't have an account?",
    "login.googleComingSoon": "Google Sign-In coming soon!",
    "login.appleComingSoon": "Apple Sign-In coming soon!",
    // Signup
    "signup.title": "Join the Game",
    "signup.subtitle": "Create your account and start solving puzzles",
    "signup.username": "Username",
    "signup.email": "Email",
    "signup.password": "Password (min 6 chars)",
    "signup.createAccount": "Create Account",
    "signup.creating": "Creating...",
    "signup.haveAccount": "Already have an account?",
    "signup.signIn": "Sign In",
    // Leaderboard
    "leaderboard.title": "LEADERBOARD",
    "leaderboard.today": "Today",
    "leaderboard.allTime": "All Time",
    "leaderboard.rank": "Rank",
    "leaderboard.player": "Player",
    "leaderboard.time": "Time",
    "leaderboard.solves": "Solves",
    // Shop
    "shop.title": "SHOP",
    "shop.avatars": "Avatars",
    "shop.titles": "Titles",
    "shop.owned": "Owned",
    "shop.equip": "Equip",
    "shop.buy": "Buy",
    // General
    "general.loading": "Loading...",
    "general.error": "Error",
    "general.success": "Success",
    "general.cancel": "Cancel",
    "general.save": "Save",
    "general.delete": "Delete",
    "general.back": "Back",
    "general.next": "Next",
    "general.submit": "Submit",
    "general.search": "Search...",
  },
  hu: {
    "nav.home": "Főoldal",
    "nav.leaderboard": "Ranglista",
    "nav.practice": "Gyakorlás",
    "nav.shop": "Bolt",
    "nav.friends": "Barátok",
    "nav.lobbies": "Lobbik",
    "nav.community": "Közösség",
    "nav.profile": "Profil",
    "nav.login": "Belépés",
    "nav.settings": "Beállítások",
    "hero.title": "Logic",
    "hero.title2": "Guesser",
    "hero.subtitle": "Teszteld az agyadat napi fejtörőkkel, csatázz barátaiddal és mássz fel a globális ranglistán.",
    "hero.daily": "Napi Kihívás Indítása",
    "hero.practice": "Gyakorló Mód",
    "hero.badge": "Új napi kihívás elérhető",
    "hero.statPuzzles": "Megoldott fejtörők",
    "hero.statPlayers": "Aktív játékosok",
    "hero.statDaily": "Napi kihívások",
    "profile.level": "Szint",
    "profile.streak": "Sorozat",
    "profile.solved": "Megoldva",
    "profile.credits": "Kreditek",
    "profile.logout": "Kijelentkezés",
    "profile.editBio": "Bio szerkesztése",
    "profile.addBio": "Bio hozzáadása",
    "profile.noBio": "Még nincs bio",
    "profile.editName": "Név szerkesztése",
    "profile.upgradePro": "Váltás Pro-ra",
    "profile.goPro": "Pro",
    "profile.changeName": "Felhasználónév változtatás",
    "profile.saveName": "Mentés",
    "settings.title": "BEÁLLÍTÁSOK",
    "settings.notifications": "Értesítések",
    "settings.notificationsDesc": "Alkalmazáson belüli értesítések engedélyezése",
    "settings.battleInvites": "Csata meghívók",
    "settings.battleInvitesDesc": "Értesítés ha valaki csatára hív",
    "settings.creditRewards": "Kredit jutalmak",
    "settings.creditRewardsDesc": "Értesítés ha kreditet kapsz",
    "settings.friendRequests": "Barátkérelmek",
    "settings.friendRequestsDesc": "Értesítés új barátkérelmekről",
    "settings.sound": "Hangeffektek",
    "settings.soundDesc": "Hangok lejátszása játék eseményeknél",
    "settings.email": "Email értesítések",
    "settings.emailDesc": "Email értesítések fontos eseményekről",
    "settings.save": "Beállítások mentése",
    "settings.changePassword": "Jelszó változtatás",
    "settings.changePasswordDesc": "Fiók jelszó frissítése",
    "settings.newPassword": "Új jelszó (min 6 karakter)",
    "settings.confirmPassword": "Jelszó megerősítése",
    "settings.updatePassword": "Jelszó frissítése",
    "settings.updating": "Frissítés...",
    "settings.loggedInAs": "Bejelentkezve mint:",
    "settings.language": "Nyelv",
    "settings.languageDesc": "Válassz nyelvet",
    "login.title": "Üdv újra",
    "login.subtitle": "Jelentkezz be a fejtörős utad folytatásához",
    "login.email": "Email",
    "login.password": "Jelszó",
    "login.signIn": "Bejelentkezés",
    "login.signingIn": "Bejelentkezés...",
    "login.forgotPassword": "Elfelejtett jelszó?",
    "login.noAccount": "Még nincs fiókod?",
    "login.createAccount": "Fiók létrehozása",
    "login.orSignUp": "Lehet, hogy nincs fiókod?",
    "login.googleComingSoon": "Google bejelentkezés hamarosan!",
    "login.appleComingSoon": "Apple bejelentkezés hamarosan!",
    "signup.title": "Csatlakozz",
    "signup.subtitle": "Hozd létre fiókodat és kezdj fejtörőket megoldani",
    "signup.username": "Felhasználónév",
    "signup.email": "Email",
    "signup.password": "Jelszó (min 6 karakter)",
    "signup.createAccount": "Fiók létrehozása",
    "signup.creating": "Létrehozás...",
    "signup.haveAccount": "Már van fiókod?",
    "signup.signIn": "Bejelentkezés",
    "leaderboard.title": "RANGLISTA",
    "leaderboard.today": "Ma",
    "leaderboard.allTime": "Összesített",
    "leaderboard.rank": "Helyezés",
    "leaderboard.player": "Játékos",
    "leaderboard.time": "Idő",
    "leaderboard.solves": "Megoldások",
    "shop.title": "BOLT",
    "shop.avatars": "Avatarok",
    "shop.titles": "Címek",
    "shop.owned": "Megvan",
    "shop.equip": "Felszerel",
    "shop.buy": "Vásárlás",
    "general.loading": "Betöltés...",
    "general.error": "Hiba",
    "general.success": "Sikeres",
    "general.cancel": "Mégse",
    "general.save": "Mentés",
    "general.delete": "Törlés",
    "general.back": "Vissza",
    "general.next": "Következő",
    "general.submit": "Beküldés",
    "general.search": "Keresés...",
  },
  la: {
    "nav.home": "Domus",
    "nav.leaderboard": "Tabula",
    "nav.practice": "Exercitium",
    "nav.shop": "Taberna",
    "nav.friends": "Amici",
    "nav.lobbies": "Atria",
    "nav.community": "Communitas",
    "nav.profile": "Profanum",
    "nav.login": "Inire",
    "nav.settings": "Optiones",
    "hero.title": "Logic",
    "hero.title2": "Guesser",
    "hero.subtitle": "Proba ingenium tuum cum aenigmatibus diurnis, pugna cum amicis, et ascende tabulam globalem.",
    "hero.daily": "Provocatio Diurna",
    "hero.practice": "Modus Exercitii",
    "hero.badge": "Nova provocatio diurna praesto est",
    "hero.statPuzzles": "Aenigmata Soluta",
    "hero.statPlayers": "Lusores Activi",
    "hero.statDaily": "Provocationes Diurnae",
    "profile.level": "Gradus",
    "profile.streak": "Series",
    "profile.solved": "Soluta",
    "profile.credits": "Nummi",
    "profile.logout": "Exire",
    "profile.editBio": "Mutare bio",
    "profile.addBio": "Addere bio",
    "profile.noBio": "Nulla bio adhuc",
    "profile.editName": "Mutare nomen",
    "profile.upgradePro": "Ad Pro",
    "profile.goPro": "Pro",
    "profile.changeName": "Mutare Nomen",
    "profile.saveName": "Servare",
    "settings.title": "OPTIONES",
    "settings.notifications": "Nuntii",
    "settings.notificationsDesc": "Permittere nuntios in applicatione",
    "settings.battleInvites": "Invitationes Pugnae",
    "settings.battleInvitesDesc": "Nuntiari cum quis te ad pugnam invitat",
    "settings.creditRewards": "Praemia Nummorum",
    "settings.creditRewardsDesc": "Nuntiari cum nummos accipis",
    "settings.friendRequests": "Petitiones Amicitiae",
    "settings.friendRequestsDesc": "Nuntiari de novis petitionibus amicitiae",
    "settings.sound": "Effectus Sonorum",
    "settings.soundDesc": "Sonos ludere pro eventibus ludi",
    "settings.email": "Nuntii Electronici",
    "settings.emailDesc": "Accipere nuntios electronicos de rebus magni momenti",
    "settings.save": "Optiones Servare",
    "settings.changePassword": "Mutare Tesseram",
    "settings.changePasswordDesc": "Tesseram rationis renovare",
    "settings.newPassword": "Nova tessera (min 6 litt.)",
    "settings.confirmPassword": "Confirmare tesseram",
    "settings.updatePassword": "Tesseram Renovare",
    "settings.updating": "Renovans...",
    "settings.loggedInAs": "Sessio ut:",
    "settings.language": "Lingua",
    "settings.languageDesc": "Elige linguam tuam",
    "login.title": "Salve Iterum",
    "login.subtitle": "Inire ut iter aenigmatum tuum prosequaris",
    "login.email": "Epistula Electronica",
    "login.password": "Tessera",
    "login.signIn": "Inire",
    "login.signingIn": "Iniens...",
    "login.forgotPassword": "Tesseram oblitus?",
    "login.noAccount": "Nondum habes rationem?",
    "login.createAccount": "Creare Rationem",
    "login.orSignUp": "Fortasse rationem non habes?",
    "login.googleComingSoon": "Google mox veniet!",
    "login.appleComingSoon": "Apple mox veniet!",
    "signup.title": "Iunge Te",
    "signup.subtitle": "Crea rationem tuam et incipe aenigmata solvere",
    "signup.username": "Nomen Usoris",
    "signup.email": "Epistula Electronica",
    "signup.password": "Tessera (min 6 litt.)",
    "signup.createAccount": "Creare Rationem",
    "signup.creating": "Creans...",
    "signup.haveAccount": "Iam habes rationem?",
    "signup.signIn": "Inire",
    "leaderboard.title": "TABULA",
    "leaderboard.today": "Hodie",
    "leaderboard.allTime": "Omni Tempore",
    "leaderboard.rank": "Ordo",
    "leaderboard.player": "Lusor",
    "leaderboard.time": "Tempus",
    "leaderboard.solves": "Solutiones",
    "shop.title": "TABERNA",
    "shop.avatars": "Imagines",
    "shop.titles": "Tituli",
    "shop.owned": "Possessum",
    "shop.equip": "Induere",
    "shop.buy": "Emere",
    "general.loading": "Onerans...",
    "general.error": "Error",
    "general.success": "Successus",
    "general.cancel": "Abrogare",
    "general.save": "Servare",
    "general.delete": "Delere",
    "general.back": "Retro",
    "general.next": "Proximus",
    "general.submit": "Submittere",
    "general.search": "Quaerere...",
  },
  el: {
    "nav.home": "Αρχική",
    "nav.leaderboard": "Κατάταξη",
    "nav.practice": "Εξάσκηση",
    "nav.shop": "Κατάστημα",
    "nav.friends": "Φίλοι",
    "nav.lobbies": "Αίθουσες",
    "nav.community": "Κοινότητα",
    "nav.profile": "Προφίλ",
    "nav.login": "Σύνδεση",
    "nav.settings": "Ρυθμίσεις",
    "hero.title": "Logic",
    "hero.title2": "Guesser",
    "hero.subtitle": "Δοκίμασε τη λογική σου με καθημερινά γρίφους, πολέμησε με φίλους και ανέβα στην παγκόσμια κατάταξη.",
    "hero.daily": "Ημερήσια Πρόκληση",
    "hero.practice": "Λειτουργία Εξάσκησης",
    "hero.badge": "Νέα ημερήσια πρόκληση διαθέσιμη",
    "hero.statPuzzles": "Γρίφοι Λυμένοι",
    "hero.statPlayers": "Ενεργοί Παίκτες",
    "hero.statDaily": "Ημερήσιες Προκλήσεις",
    "profile.level": "Επίπεδο",
    "profile.streak": "Σειρά",
    "profile.solved": "Λυμένα",
    "profile.credits": "Πόντοι",
    "profile.logout": "Αποσύνδεση",
    "profile.editBio": "Επεξεργασία bio",
    "profile.addBio": "Προσθήκη bio",
    "profile.noBio": "Χωρίς bio ακόμα",
    "profile.editName": "Αλλαγή ονόματος",
    "profile.upgradePro": "Αναβάθμιση σε Pro",
    "profile.goPro": "Pro",
    "profile.changeName": "Αλλαγή Ονόματος",
    "profile.saveName": "Αποθήκευση",
    "settings.title": "ΡΥΘΜΙΣΕΙΣ",
    "settings.notifications": "Ειδοποιήσεις",
    "settings.notificationsDesc": "Ενεργοποίηση ειδοποιήσεων στην εφαρμογή",
    "settings.battleInvites": "Προσκλήσεις Μάχης",
    "settings.battleInvitesDesc": "Ειδοποίηση όταν κάποιος σε προσκαλεί σε μάχη",
    "settings.creditRewards": "Ανταμοιβές Πόντων",
    "settings.creditRewardsDesc": "Ειδοποίηση όταν κερδίζεις πόντους",
    "settings.friendRequests": "Αιτήματα Φιλίας",
    "settings.friendRequestsDesc": "Ειδοποίηση για νέα αιτήματα φιλίας",
    "settings.sound": "Ηχητικά Εφέ",
    "settings.soundDesc": "Αναπαραγωγή ήχων για γεγονότα παιχνιδιού",
    "settings.email": "Ειδοποιήσεις Email",
    "settings.emailDesc": "Λήψη email για σημαντικά γεγονότα",
    "settings.save": "Αποθήκευση Ρυθμίσεων",
    "settings.changePassword": "Αλλαγή Κωδικού",
    "settings.changePasswordDesc": "Ενημέρωση κωδικού λογαριασμού",
    "settings.newPassword": "Νέος κωδικός (ελάχ. 6 χαρ.)",
    "settings.confirmPassword": "Επιβεβαίωση κωδικού",
    "settings.updatePassword": "Ενημέρωση Κωδικού",
    "settings.updating": "Ενημέρωση...",
    "settings.loggedInAs": "Συνδεδεμένος ως:",
    "settings.language": "Γλώσσα",
    "settings.languageDesc": "Επιλέξτε τη γλώσσα σας",
    "login.title": "Καλώς Ήρθες",
    "login.subtitle": "Συνδέσου για να συνεχίσεις το ταξίδι σου",
    "login.email": "Email",
    "login.password": "Κωδικός",
    "login.signIn": "Σύνδεση",
    "login.signingIn": "Σύνδεση...",
    "login.forgotPassword": "Ξεχάσατε τον κωδικό;",
    "login.noAccount": "Δεν έχετε λογαριασμό;",
    "login.createAccount": "Δημιουργία Λογαριασμού",
    "login.orSignUp": "Μήπως δεν έχετε λογαριασμό;",
    "login.googleComingSoon": "Google σύντομα!",
    "login.appleComingSoon": "Apple σύντομα!",
    "signup.title": "Γίνε Μέλος",
    "signup.subtitle": "Δημιούργησε λογαριασμό και ξεκίνα να λύνεις γρίφους",
    "signup.username": "Όνομα Χρήστη",
    "signup.email": "Email",
    "signup.password": "Κωδικός (ελάχ. 6 χαρ.)",
    "signup.createAccount": "Δημιουργία Λογαριασμού",
    "signup.creating": "Δημιουργία...",
    "signup.haveAccount": "Έχετε ήδη λογαριασμό;",
    "signup.signIn": "Σύνδεση",
    "leaderboard.title": "ΚΑΤΆΤΑΞΗ",
    "leaderboard.today": "Σήμερα",
    "leaderboard.allTime": "Συνολικά",
    "leaderboard.rank": "Θέση",
    "leaderboard.player": "Παίκτης",
    "leaderboard.time": "Χρόνος",
    "leaderboard.solves": "Λύσεις",
    "shop.title": "ΚΑΤΑΣΤΗΜΑ",
    "shop.avatars": "Άβαταρ",
    "shop.titles": "Τίτλοι",
    "shop.owned": "Ιδιοκτησία",
    "shop.equip": "Εξοπλισμός",
    "shop.buy": "Αγορά",
    "general.loading": "Φόρτωση...",
    "general.error": "Σφάλμα",
    "general.success": "Επιτυχία",
    "general.cancel": "Ακύρωση",
    "general.save": "Αποθήκευση",
    "general.delete": "Διαγραφή",
    "general.back": "Πίσω",
    "general.next": "Επόμενο",
    "general.submit": "Υποβολή",
    "general.search": "Αναζήτηση...",
  },
  zh: {
    "nav.home": "首页",
    "nav.leaderboard": "排行榜",
    "nav.practice": "练习",
    "nav.shop": "商店",
    "nav.friends": "好友",
    "nav.lobbies": "大厅",
    "nav.community": "社区",
    "nav.profile": "个人资料",
    "nav.login": "登录",
    "nav.settings": "设置",
    "hero.title": "Logic",
    "hero.title2": "Guesser",
    "hero.subtitle": "用每日谜题测试你的脑力，与朋友对战，攀登全球排行榜。",
    "hero.daily": "开始每日挑战",
    "hero.practice": "练习模式",
    "hero.badge": "新的每日挑战已发布",
    "hero.statPuzzles": "已解谜题",
    "hero.statPlayers": "活跃玩家",
    "hero.statDaily": "每日挑战",
    "profile.level": "等级",
    "profile.streak": "连胜",
    "profile.solved": "已解决",
    "profile.credits": "积分",
    "profile.logout": "退出",
    "profile.editBio": "编辑简介",
    "profile.addBio": "添加简介",
    "profile.noBio": "暂无简介",
    "profile.editName": "修改名字",
    "profile.upgradePro": "升级到Pro",
    "profile.goPro": "Pro",
    "profile.changeName": "更改用户名",
    "profile.saveName": "保存",
    "settings.title": "设置",
    "settings.notifications": "通知",
    "settings.notificationsDesc": "启用应用内通知",
    "settings.battleInvites": "对战邀请",
    "settings.battleInvitesDesc": "有人邀请你对战时通知",
    "settings.creditRewards": "积分奖励",
    "settings.creditRewardsDesc": "获得积分时通知",
    "settings.friendRequests": "好友请求",
    "settings.friendRequestsDesc": "新好友请求通知",
    "settings.sound": "音效",
    "settings.soundDesc": "游戏事件播放声音",
    "settings.email": "邮件通知",
    "settings.emailDesc": "接收重要事件邮件提醒",
    "settings.save": "保存设置",
    "settings.changePassword": "修改密码",
    "settings.changePasswordDesc": "更新账户密码",
    "settings.newPassword": "新密码（至少6位）",
    "settings.confirmPassword": "确认新密码",
    "settings.updatePassword": "更新密码",
    "settings.updating": "更新中...",
    "settings.loggedInAs": "登录为：",
    "settings.language": "语言",
    "settings.languageDesc": "选择您的首选语言",
    "login.title": "欢迎回来",
    "login.subtitle": "登录以继续你的解谜之旅",
    "login.email": "邮箱",
    "login.password": "密码",
    "login.signIn": "登录",
    "login.signingIn": "登录中...",
    "login.forgotPassword": "忘记密码？",
    "login.noAccount": "还没有账户？",
    "login.createAccount": "创建账户",
    "login.orSignUp": "也许你没有账户？",
    "login.googleComingSoon": "Google登录即将推出！",
    "login.appleComingSoon": "Apple登录即将推出！",
    "signup.title": "加入游戏",
    "signup.subtitle": "创建账户并开始解谜",
    "signup.username": "用户名",
    "signup.email": "邮箱",
    "signup.password": "密码（至少6位）",
    "signup.createAccount": "创建账户",
    "signup.creating": "创建中...",
    "signup.haveAccount": "已有账户？",
    "signup.signIn": "登录",
    "leaderboard.title": "排行榜",
    "leaderboard.today": "今天",
    "leaderboard.allTime": "全部",
    "leaderboard.rank": "排名",
    "leaderboard.player": "玩家",
    "leaderboard.time": "时间",
    "leaderboard.solves": "解题数",
    "shop.title": "商店",
    "shop.avatars": "头像",
    "shop.titles": "称号",
    "shop.owned": "已拥有",
    "shop.equip": "装备",
    "shop.buy": "购买",
    "general.loading": "加载中...",
    "general.error": "错误",
    "general.success": "成功",
    "general.cancel": "取消",
    "general.save": "保存",
    "general.delete": "删除",
    "general.back": "返回",
    "general.next": "下一步",
    "general.submit": "提交",
    "general.search": "搜索...",
  },
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType>({
  language: "en",
  setLanguage: () => {},
  t: (key) => key,
});

export const useLanguage = () => useContext(LanguageContext);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem("logicguesser-lang");
    return (saved as Language) || "en";
  });

  const setLanguage = useCallback((lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem("logicguesser-lang", lang);
  }, []);

  const t = useCallback((key: string) => {
    return translations[language]?.[key] || translations.en[key] || key;
  }, [language]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}
