import { createContext, useContext, useState, ReactNode, useCallback } from "react";

export type Language = "en" | "hu" | "la" | "el" | "zh";

export const LANGUAGE_LABELS: Record<Language, string> = {
  en: "English",
  hu: "Magyar",
  la: "Latina",
  el: "Ελληνικά",
  zh: "中文",
};

export const LANGUAGE_FLAGS: Record<Language, string> = {
  en: "🇬🇧",
  hu: "🇭🇺",
  la: "🏛️",
  el: "🇬🇷",
  zh: "🇨🇳",
};

const en: Record<string, string> = {
  // Nav
  "nav.home": "Home",
  "nav.leaderboard": "Leaderboard",
  "nav.practice": "Practice",
  "nav.shop": "Shop",
  "nav.friends": "Friends",
  "nav.lobbies": "Lobbies",
  "nav.community": "Community",
  "nav.profile": "Profile",
  "nav.login": "Login",
  "nav.settings": "Settings",
  // Hero
  "hero.title": "Logic",
  "hero.title2": "Guesser",
  "hero.subtitle": "Test your brainpower with daily puzzles, battle friends, and climb the global leaderboard.",
  "hero.daily": "Start Daily Challenge",
  "hero.practice": "Practice Mode",
  "hero.badge": "New Daily Challenge Available",
  "hero.statPuzzles": "Puzzles Solved",
  "hero.statPlayers": "Active Players",
  "hero.statDaily": "Daily Challenges",
  // Profile
  "profile.level": "Level",
  "profile.streak": "Streak",
  "profile.solved": "Solved",
  "profile.credits": "Credits",
  "profile.logout": "Log Out",
  "profile.editBio": "Edit bio",
  "profile.addBio": "Add bio",
  "profile.noBio": "No bio yet",
  "profile.editName": "Edit name",
  "profile.upgradePro": "Upgrade to Pro",
  "profile.goPro": "Go Pro",
  "profile.changeName": "Change Username",
  "profile.saveName": "Save",
  // Settings
  "settings.title": "SETTINGS",
  "settings.notifications": "Notifications",
  "settings.notificationsDesc": "Enable in-app notifications",
  "settings.battleInvites": "Battle Invites",
  "settings.battleInvitesDesc": "Get notified when someone invites you to battle",
  "settings.creditRewards": "Credit Rewards",
  "settings.creditRewardsDesc": "Get notified when you earn credits",
  "settings.friendRequests": "Friend Requests",
  "settings.friendRequestsDesc": "Get notified about new friend requests",
  "settings.sound": "Sound Effects",
  "settings.soundDesc": "Play sounds for game events",
  "settings.email": "Email Notifications",
  "settings.emailDesc": "Receive email alerts for important events",
  "settings.save": "Save Settings",
  "settings.changePassword": "Change Password",
  "settings.changePasswordDesc": "Update your account password",
  "settings.newPassword": "New password (min 6 chars)",
  "settings.confirmPassword": "Confirm new password",
  "settings.updatePassword": "Update Password",
  "settings.updating": "Updating...",
  "settings.loggedInAs": "Logged in as:",
  "settings.language": "Language",
  "settings.languageDesc": "Choose your preferred language",
  // Login
  "login.title": "LOG",
  "login.title2": "IN",
  "login.subtitle": "Welcome back, challenger.",
  "login.email": "Email",
  "login.password": "Password",
  "login.signIn": "Sign In",
  "login.signingIn": "Signing in...",
  "login.forgotPassword": "Forgot your password?",
  "login.noAccount": "Can't log in? Maybe you don't have an account yet?",
  "login.createAccount": "Create an Account",
  "login.or": "or",
  "login.google": "Continue with Google",
  "login.apple": "Continue with Apple",
  // Signup
  "signup.title": "SIGN",
  "signup.title2": "UP",
  "signup.subtitle": "Join the challenge. Prove your logic.",
  "signup.username": "Username",
  "signup.email": "Email",
  "signup.password": "Password (min 6 chars)",
  "signup.createAccount": "Create Account",
  "signup.creating": "Creating account...",
  "signup.haveAccount": "Already have an account?",
  "signup.signIn": "Log in",
  "signup.or": "or",
  "signup.google": "Continue with Google",
  "signup.apple": "Continue with Apple",
  "signup.checkInbox": "CHECK YOUR",
  "signup.checkInbox2": "INBOX",
  "signup.verifyMsg": "We sent a verification email to:",
  "signup.verifyAction": "Click the link in the email to verify your account, then come back and log in.",
  "signup.goLogin": "Go to Login",
  "signup.badUsername": "That username contains inappropriate language. Please choose another.",
  // Daily Challenge
  "daily.title": "DAILY",
  "daily.title2": "CHALLENGE",
  "daily.complete": "CHALLENGE",
  "daily.complete2": "COMPLETE",
  "daily.dayStreak": "day streak",
  "daily.solvedIn": "You solved today's challenge in",
  "daily.retryChallenge": "Retry Challenge",
  "daily.left": "left",
  "daily.proPerk": "Pro perk",
  "daily.restartFor": "Restart for",
  "daily.credits": "Credits",
  "daily.discountDay": "Discount day!",
  "daily.retriesUsed": "All retries used today.",
  "daily.comeBack": "Come back tomorrow for a new challenge!",
  "daily.getProRetries": "Get Pro for retries",
  "daily.viewLeaderboard": "View Leaderboard",
  "daily.noPuzzle": "No Puzzle Today",
  "daily.checkBack": "Check back tomorrow!",
  "daily.tasksToday": "Today's challenge has",
  "daily.tasks": "tasks",
  "daily.wrongPenalty": "Wrong answers add +5 seconds. Your total time goes on the leaderboard.",
  "daily.start": "Start Challenge",
  "daily.allComplete": "All Tasks Complete!",
  "daily.totalTime": "Total Time:",
  "daily.penaltyIncl": "Includes",
  "daily.inPenalties": "in penalties",
  "daily.task": "Task",
  "daily.of": "of",
  "daily.penalties": "penalties",
  "daily.yourAnswer": "Your answer...",
  "daily.wrong5s": "Wrong! +5 seconds penalty",
  "daily.correct": "correct! Next task...",
  "daily.creditBonus": "credit bonus!",
  // Practice
  "practice.title": "PRACTICE",
  "practice.title2": "MODE",
  "practice.streak": "Streak:",
  "practice.perSolve": "credits per solve",
  "practice.all": "All",
  "practice.correct": "Correct!",
  "practice.solvedIn": "Solved in",
  "practice.next": "Next Puzzle",
  "practice.skip": "Skip",
  "practice.yourAnswer": "Your answer...",
  "practice.wrongTryAgain": "Wrong answer! Try again.",
  // Leaderboard
  "leaderboard.title": "LEADER",
  "leaderboard.title2": "BOARD",
  "leaderboard.subtitle": "Today's fastest solvers",
  "leaderboard.noOne": "No one has completed today's challenge yet. Be the first!",
  "leaderboard.sent": "Sent",
  // Shop
  "shop.title": "SHOP",
  "shop.credits": "Credits",
  "shop.avatars": "Avatars",
  "shop.proExclusive": "Pro Exclusive",
  "shop.themes": "Themes",
  "shop.titleBadges": "Title Badges",
  "shop.buyCredits": "Buy Credits",
  "shop.equipped": "Equipped",
  "shop.equip": "Equip",
  "shop.buy": "Buy",
  "shop.owned": "Owned",
  "shop.active": "Active",
  "shop.apply": "Apply",
  "shop.purchase": "Purchase",
  "shop.getPro": "Get Pro",
  "shop.earnDaily": "Earn",
  "shop.earnDailyCredits": "credits",
  "shop.forEveryDaily": "for every Daily Challenge",
  "shop.upgradeProShop": "Upgrade to Pro for exclusive avatars & 2× credits",
  "shop.themeApplied": "Theme applied!",
  // Friends
  "friends.title": "FRIEND",
  "friends.title2": "S",
  "friends.searchPlaceholder": "Search by username...",
  "friends.alreadyConnected": "Already connected",
  "friends.add": "Add",
  "friends.friends": "Friends",
  "friends.requests": "Requests",
  "friends.noFriends": "No friends yet. Search for players above!",
  "friends.incoming": "Incoming",
  "friends.accept": "Accept",
  "friends.sent": "Sent",
  "friends.pending": "Pending...",
  "friends.noRequests": "No pending requests.",
  "friends.requestSent": "Friend request sent!",
  "friends.alreadySent": "Request already sent!",
  "friends.failed": "Failed to send request",
  "friends.added": "Friend added!",
  "friends.declined": "Request declined",
  // General
  "general.loading": "Loading...",
  "general.error": "Error",
  "general.success": "Success",
  "general.cancel": "Cancel",
  "general.save": "Save",
  "general.delete": "Delete",
  "general.back": "Back",
  "general.next": "Next",
  "general.submit": "Submit",
  "general.search": "Search...",
  "general.welcomeBack": "Welcome back!",
  "general.2xPro": "2× Pro",
  "general.2xEarn": "2× EARN",
};

const hu: Record<string, string> = {
  "nav.home": "Főoldal",
  "nav.leaderboard": "Ranglista",
  "nav.practice": "Gyakorlás",
  "nav.shop": "Bolt",
  "nav.friends": "Barátok",
  "nav.lobbies": "Lobbik",
  "nav.community": "Közösség",
  "nav.profile": "Profil",
  "nav.login": "Belépés",
  "nav.settings": "Beállítások",
  "hero.title": "Logic",
  "hero.title2": "Guesser",
  "hero.subtitle": "Teszteld az agyadat napi fejtörőkkel, csatázz barátaiddal és mássz fel a globális ranglistán.",
  "hero.daily": "Napi Kihívás Indítása",
  "hero.practice": "Gyakorló Mód",
  "hero.badge": "Új napi kihívás elérhető",
  "hero.statPuzzles": "Megoldott fejtörők",
  "hero.statPlayers": "Aktív játékosok",
  "hero.statDaily": "Napi kihívások",
  "profile.level": "Szint",
  "profile.streak": "Sorozat",
  "profile.solved": "Megoldva",
  "profile.credits": "Kreditek",
  "profile.logout": "Kijelentkezés",
  "profile.editBio": "Bio szerkesztése",
  "profile.addBio": "Bio hozzáadása",
  "profile.noBio": "Még nincs bio",
  "profile.editName": "Név szerkesztése",
  "profile.upgradePro": "Váltás Pro-ra",
  "profile.goPro": "Pro",
  "profile.changeName": "Felhasználónév változtatás",
  "profile.saveName": "Mentés",
  "settings.title": "BEÁLLÍTÁSOK",
  "settings.notifications": "Értesítések",
  "settings.notificationsDesc": "Alkalmazáson belüli értesítések",
  "settings.battleInvites": "Csata meghívók",
  "settings.battleInvitesDesc": "Értesítés ha valaki csatára hív",
  "settings.creditRewards": "Kredit jutalmak",
  "settings.creditRewardsDesc": "Értesítés ha kreditet kapsz",
  "settings.friendRequests": "Barátkérelmek",
  "settings.friendRequestsDesc": "Értesítés új barátkérelmekről",
  "settings.sound": "Hangeffektek",
  "settings.soundDesc": "Hangok lejátszása",
  "settings.email": "Email értesítések",
  "settings.emailDesc": "Email értesítések fontos eseményekről",
  "settings.save": "Beállítások mentése",
  "settings.changePassword": "Jelszó változtatás",
  "settings.changePasswordDesc": "Fiók jelszó frissítése",
  "settings.newPassword": "Új jelszó (min 6 karakter)",
  "settings.confirmPassword": "Jelszó megerősítése",
  "settings.updatePassword": "Jelszó frissítése",
  "settings.updating": "Frissítés...",
  "settings.loggedInAs": "Bejelentkezve mint:",
  "settings.language": "Nyelv",
  "settings.languageDesc": "Válassz nyelvet",
  "login.title": "BELÉPÉS",
  "login.title2": "",
  "login.subtitle": "Üdv újra, kihívó.",
  "login.email": "Email",
  "login.password": "Jelszó",
  "login.signIn": "Bejelentkezés",
  "login.signingIn": "Bejelentkezés...",
  "login.forgotPassword": "Elfelejtett jelszó?",
  "login.noAccount": "Nem tudsz bejelentkezni? Lehet, hogy nincs fiókod?",
  "login.createAccount": "Fiók létrehozása",
  "login.or": "vagy",
  "login.google": "Tovább Google-lel",
  "login.apple": "Tovább Apple-lel",
  "signup.title": "REGISZTRÁ",
  "signup.title2": "CIÓ",
  "signup.subtitle": "Csatlakozz a kihíváshoz. Bizonyítsd logikádat.",
  "signup.username": "Felhasználónév",
  "signup.email": "Email",
  "signup.password": "Jelszó (min 6 karakter)",
  "signup.createAccount": "Fiók létrehozása",
  "signup.creating": "Létrehozás...",
  "signup.haveAccount": "Már van fiókod?",
  "signup.signIn": "Bejelentkezés",
  "signup.or": "vagy",
  "signup.google": "Tovább Google-lel",
  "signup.apple": "Tovább Apple-lel",
  "signup.checkInbox": "NÉZD MEG AZ",
  "signup.checkInbox2": "E-MAIL FIÓKODAT",
  "signup.verifyMsg": "Megerősítő e-mailt küldtünk ide:",
  "signup.verifyAction": "Kattints az e-mailben lévő linkre, majd gyere vissza és jelentkezz be.",
  "signup.goLogin": "Bejelentkezés",
  "signup.badUsername": "Ez a felhasználónév nem megfelelő kifejezést tartalmaz.",
  "daily.title": "NAPI",
  "daily.title2": "KIHÍVÁS",
  "daily.complete": "KIHÍVÁS",
  "daily.complete2": "TELJESÍTVE",
  "daily.dayStreak": "napos sorozat",
  "daily.solvedIn": "Ma a kihívást megoldottad ennyi idő alatt:",
  "daily.retryChallenge": "Újrapróbálás",
  "daily.left": "maradt",
  "daily.proPerk": "Pro előny",
  "daily.restartFor": "Újraindítás",
  "daily.credits": "Kreditért",
  "daily.discountDay": "Akciós nap!",
  "daily.retriesUsed": "Minden újrapróbálás elhasználva.",
  "daily.comeBack": "Gyere vissza holnap új kihívásért!",
  "daily.getProRetries": "Szerezz Pro-t az újrapróbálásért",
  "daily.viewLeaderboard": "Ranglista megtekintése",
  "daily.noPuzzle": "Ma nincs fejtörő",
  "daily.checkBack": "Nézz vissza holnap!",
  "daily.tasksToday": "A mai kihívásban",
  "daily.tasks": "feladat van",
  "daily.wrongPenalty": "Hibás válasz +5 másodperc büntetés. Az idő a ranglistára kerül.",
  "daily.start": "Kihívás indítása",
  "daily.allComplete": "Minden feladat kész!",
  "daily.totalTime": "Összidő:",
  "daily.penaltyIncl": "Ebből",
  "daily.inPenalties": "büntetés",
  "daily.task": "Feladat",
  "daily.of": "/",
  "daily.penalties": "büntetés",
  "daily.yourAnswer": "Válaszod...",
  "daily.wrong5s": "Hibás! +5 másodperc büntetés",
  "daily.correct": "helyes! Következő feladat...",
  "daily.creditBonus": "kredit bónusz!",
  "practice.title": "GYAKORLÓ",
  "practice.title2": "MÓD",
  "practice.streak": "Sorozat:",
  "practice.perSolve": "kredit megoldásonként",
  "practice.all": "Mind",
  "practice.correct": "Helyes!",
  "practice.solvedIn": "Megoldva",
  "practice.next": "Következő fejtörő",
  "practice.skip": "Kihagyás",
  "practice.yourAnswer": "Válaszod...",
  "practice.wrongTryAgain": "Hibás válasz! Próbáld újra.",
  "leaderboard.title": "RANG",
  "leaderboard.title2": "LISTA",
  "leaderboard.subtitle": "A mai leggyorsabb megoldók",
  "leaderboard.noOne": "Még senki sem oldotta meg a mai kihívást. Legyél az első!",
  "leaderboard.sent": "Elküldve",
  "shop.title": "BOLT",
  "shop.credits": "Kreditek",
  "shop.avatars": "Avatarok",
  "shop.proExclusive": "Pro Exkluzív",
  "shop.themes": "Témák",
  "shop.titleBadges": "Címek",
  "shop.buyCredits": "Kredit vásárlás",
  "shop.equipped": "Felszerelve",
  "shop.equip": "Felszerel",
  "shop.buy": "Vásárlás",
  "shop.owned": "Megvan",
  "shop.active": "Aktív",
  "shop.apply": "Alkalmaz",
  "shop.purchase": "Vásárlás",
  "shop.getPro": "Pro beszerzése",
  "shop.earnDaily": "Keress",
  "shop.earnDailyCredits": "kreditet",
  "shop.forEveryDaily": "minden napi kihívásért",
  "shop.upgradeProShop": "Váltás Pro-ra exkluzív avatarokért & 2× kreditért",
  "shop.themeApplied": "Téma alkalmazva!",
  "friends.title": "BARÁ",
  "friends.title2": "TOK",
  "friends.searchPlaceholder": "Keresés felhasználónév alapján...",
  "friends.alreadyConnected": "Már kapcsolódva",
  "friends.add": "Hozzáadás",
  "friends.friends": "Barátok",
  "friends.requests": "Kérelmek",
  "friends.noFriends": "Még nincsenek barátaid. Keress játékosokat!",
  "friends.incoming": "Bejövő",
  "friends.accept": "Elfogadás",
  "friends.sent": "Elküldve",
  "friends.pending": "Függőben...",
  "friends.noRequests": "Nincsenek függőben lévő kérelmek.",
  "friends.requestSent": "Barátkérelem elküldve!",
  "friends.alreadySent": "Kérelem már elküldve!",
  "friends.failed": "Nem sikerült elküldeni",
  "friends.added": "Barát hozzáadva!",
  "friends.declined": "Kérelem elutasítva",
  "general.loading": "Betöltés...",
  "general.error": "Hiba",
  "general.success": "Sikeres",
  "general.cancel": "Mégse",
  "general.save": "Mentés",
  "general.delete": "Törlés",
  "general.back": "Vissza",
  "general.next": "Következő",
  "general.submit": "Beküldés",
  "general.search": "Keresés...",
  "general.welcomeBack": "Üdv újra!",
  "general.2xPro": "2× Pro",
  "general.2xEarn": "2× KERESÉS",
};

const la: Record<string, string> = {
  "nav.home": "Domus",
  "nav.leaderboard": "Tabula",
  "nav.practice": "Exercitium",
  "nav.shop": "Taberna",
  "nav.friends": "Amici",
  "nav.lobbies": "Atria",
  "nav.community": "Communitas",
  "nav.profile": "Profanum",
  "nav.login": "Inire",
  "nav.settings": "Optiones",
  "hero.title": "Logic",
  "hero.title2": "Guesser",
  "hero.subtitle": "Proba ingenium tuum cum aenigmatibus diurnis, pugna cum amicis, et ascende tabulam globalem.",
  "hero.daily": "Provocatio Diurna",
  "hero.practice": "Modus Exercitii",
  "hero.badge": "Nova provocatio diurna praesto est",
  "hero.statPuzzles": "Aenigmata Soluta",
  "hero.statPlayers": "Lusores Activi",
  "hero.statDaily": "Provocationes Diurnae",
  "profile.level": "Gradus",
  "profile.streak": "Series",
  "profile.solved": "Soluta",
  "profile.credits": "Nummi",
  "profile.logout": "Exire",
  "profile.editBio": "Mutare bio",
  "profile.addBio": "Addere bio",
  "profile.noBio": "Nulla bio adhuc",
  "profile.editName": "Mutare nomen",
  "profile.upgradePro": "Ad Pro",
  "profile.goPro": "Pro",
  "profile.changeName": "Mutare Nomen",
  "profile.saveName": "Servare",
  "settings.title": "OPTIONES",
  "settings.notifications": "Nuntii",
  "settings.notificationsDesc": "Permittere nuntios",
  "settings.battleInvites": "Invitationes Pugnae",
  "settings.battleInvitesDesc": "Nuntiari cum quis te ad pugnam invitat",
  "settings.creditRewards": "Praemia Nummorum",
  "settings.creditRewardsDesc": "Nuntiari cum nummos accipis",
  "settings.friendRequests": "Petitiones Amicitiae",
  "settings.friendRequestsDesc": "Nuntiari de novis petitionibus",
  "settings.sound": "Effectus Sonorum",
  "settings.soundDesc": "Sonos ludere pro eventibus",
  "settings.email": "Nuntii Electronici",
  "settings.emailDesc": "Accipere nuntios electronicos",
  "settings.save": "Optiones Servare",
  "settings.changePassword": "Mutare Tesseram",
  "settings.changePasswordDesc": "Tesseram renovare",
  "settings.newPassword": "Nova tessera (min 6)",
  "settings.confirmPassword": "Confirmare tesseram",
  "settings.updatePassword": "Tesseram Renovare",
  "settings.updating": "Renovans...",
  "settings.loggedInAs": "Sessio ut:",
  "settings.language": "Lingua",
  "settings.languageDesc": "Elige linguam tuam",
  "login.title": "INI",
  "login.title2": "RE",
  "login.subtitle": "Salve iterum, provocator.",
  "login.email": "Epistula",
  "login.password": "Tessera",
  "login.signIn": "Inire",
  "login.signingIn": "Iniens...",
  "login.forgotPassword": "Tesseram oblitus?",
  "login.noAccount": "Nondum habes rationem?",
  "login.createAccount": "Creare Rationem",
  "login.or": "vel",
  "login.google": "Cum Google",
  "login.apple": "Cum Apple",
  "signup.title": "INSCRI",
  "signup.title2": "BERE",
  "signup.subtitle": "Iunge provocatio. Proba logicam.",
  "signup.username": "Nomen",
  "signup.email": "Epistula",
  "signup.password": "Tessera (min 6)",
  "signup.createAccount": "Creare Rationem",
  "signup.creating": "Creans...",
  "signup.haveAccount": "Iam habes rationem?",
  "signup.signIn": "Inire",
  "signup.or": "vel",
  "signup.google": "Cum Google",
  "signup.apple": "Cum Apple",
  "signup.checkInbox": "INSPICE",
  "signup.checkInbox2": "EPISTULAM",
  "signup.verifyMsg": "Misimus epistulam ad:",
  "signup.verifyAction": "Clicca vinculum in epistula tua.",
  "signup.goLogin": "Ad Initium",
  "signup.badUsername": "Nomen non convenit.",
  "daily.title": "PROVOCATIO",
  "daily.title2": "DIURNA",
  "daily.complete": "PROVOCATIO",
  "daily.complete2": "PERFECTA",
  "daily.dayStreak": "dierum series",
  "daily.solvedIn": "Hodie solvisti in",
  "daily.retryChallenge": "Iterum Temptare",
  "daily.left": "relicti",
  "daily.proPerk": "Pro beneficium",
  "daily.restartFor": "Renovare pro",
  "daily.credits": "Nummis",
  "daily.discountDay": "Dies reductionis!",
  "daily.retriesUsed": "Omnes conatus usi.",
  "daily.comeBack": "Redi cras!",
  "daily.getProRetries": "Pro pro conatis",
  "daily.viewLeaderboard": "Videre Tabulam",
  "daily.noPuzzle": "Nullum Aenigma Hodie",
  "daily.checkBack": "Redi cras!",
  "daily.tasksToday": "Hodie provocatio habet",
  "daily.tasks": "opera",
  "daily.wrongPenalty": "Falsa +5 secundae. Tempus in tabula erit.",
  "daily.start": "Incipere",
  "daily.allComplete": "Omnia Perfecta!",
  "daily.totalTime": "Tempus Totum:",
  "daily.penaltyIncl": "Includit",
  "daily.inPenalties": "poenis",
  "daily.task": "Opus",
  "daily.of": "/",
  "daily.penalties": "poenae",
  "daily.yourAnswer": "Responsum tuum...",
  "daily.wrong5s": "Falsum! +5 secundae",
  "daily.correct": "rectum! Proximus...",
  "daily.creditBonus": "nummorum bonus!",
  "practice.title": "MODUS",
  "practice.title2": "EXERCITII",
  "practice.streak": "Series:",
  "practice.perSolve": "nummi per solutionem",
  "practice.all": "Omnes",
  "practice.correct": "Rectum!",
  "practice.solvedIn": "Solutum in",
  "practice.next": "Proximum Aenigma",
  "practice.skip": "Omittere",
  "practice.yourAnswer": "Responsum tuum...",
  "practice.wrongTryAgain": "Falsum! Iterum tempta.",
  "leaderboard.title": "TABU",
  "leaderboard.title2": "LA",
  "leaderboard.subtitle": "Velocissimi hodie",
  "leaderboard.noOne": "Nemo adhuc solvit. Esto primus!",
  "leaderboard.sent": "Missum",
  "shop.title": "TABERNA",
  "shop.credits": "Nummi",
  "shop.avatars": "Imagines",
  "shop.proExclusive": "Pro Exclusivum",
  "shop.themes": "Themata",
  "shop.titleBadges": "Tituli",
  "shop.buyCredits": "Emere Nummos",
  "shop.equipped": "Indutum",
  "shop.equip": "Induere",
  "shop.buy": "Emere",
  "shop.owned": "Possessum",
  "shop.active": "Activum",
  "shop.apply": "Applicare",
  "shop.purchase": "Emere",
  "shop.getPro": "Pro",
  "shop.earnDaily": "Accipe",
  "shop.earnDailyCredits": "nummos",
  "shop.forEveryDaily": "pro omni provocatio diurna",
  "shop.upgradeProShop": "Ad Pro pro exclusivis & 2× nummis",
  "shop.themeApplied": "Thema applicatum!",
  "friends.title": "AMI",
  "friends.title2": "CI",
  "friends.searchPlaceholder": "Quaerere per nomen...",
  "friends.alreadyConnected": "Iam coniunctum",
  "friends.add": "Addere",
  "friends.friends": "Amici",
  "friends.requests": "Petitiones",
  "friends.noFriends": "Nulli amici adhuc. Quaere lusores!",
  "friends.incoming": "Venientes",
  "friends.accept": "Accipere",
  "friends.sent": "Missum",
  "friends.pending": "Pendens...",
  "friends.noRequests": "Nullae petitiones.",
  "friends.requestSent": "Petitio missa!",
  "friends.alreadySent": "Petitio iam missa!",
  "friends.failed": "Non potuit mittere",
  "friends.added": "Amicus additus!",
  "friends.declined": "Petitio recusata",
  "general.loading": "Onerans...",
  "general.error": "Error",
  "general.success": "Successus",
  "general.cancel": "Abrogare",
  "general.save": "Servare",
  "general.delete": "Delere",
  "general.back": "Retro",
  "general.next": "Proximus",
  "general.submit": "Submittere",
  "general.search": "Quaerere...",
  "general.welcomeBack": "Salve iterum!",
  "general.2xPro": "2× Pro",
  "general.2xEarn": "2× LUCRA",
};

const el: Record<string, string> = {
  "nav.home": "Αρχική",
  "nav.leaderboard": "Κατάταξη",
  "nav.practice": "Εξάσκηση",
  "nav.shop": "Κατάστημα",
  "nav.friends": "Φίλοι",
  "nav.lobbies": "Αίθουσες",
  "nav.community": "Κοινότητα",
  "nav.profile": "Προφίλ",
  "nav.login": "Σύνδεση",
  "nav.settings": "Ρυθμίσεις",
  "hero.title": "Logic",
  "hero.title2": "Guesser",
  "hero.subtitle": "Δοκίμασε τη λογική σου με καθημερινούς γρίφους, πολέμησε φίλους και ανέβα στην κατάταξη.",
  "hero.daily": "Ημερήσια Πρόκληση",
  "hero.practice": "Εξάσκηση",
  "hero.badge": "Νέα ημερήσια πρόκληση",
  "hero.statPuzzles": "Γρίφοι Λυμένοι",
  "hero.statPlayers": "Ενεργοί Παίκτες",
  "hero.statDaily": "Ημερήσιες Προκλήσεις",
  "profile.level": "Επίπεδο",
  "profile.streak": "Σειρά",
  "profile.solved": "Λυμένα",
  "profile.credits": "Πόντοι",
  "profile.logout": "Αποσύνδεση",
  "profile.editBio": "Επεξεργασία bio",
  "profile.addBio": "Προσθήκη bio",
  "profile.noBio": "Χωρίς bio",
  "profile.editName": "Αλλαγή ονόματος",
  "profile.upgradePro": "Αναβάθμιση σε Pro",
  "profile.goPro": "Pro",
  "profile.changeName": "Αλλαγή Ονόματος",
  "profile.saveName": "Αποθήκευση",
  "settings.title": "ΡΥΘΜΙΣΕΙΣ",
  "settings.notifications": "Ειδοποιήσεις",
  "settings.notificationsDesc": "Ενεργοποίηση ειδοποιήσεων",
  "settings.battleInvites": "Προσκλήσεις Μάχης",
  "settings.battleInvitesDesc": "Ειδοποίηση για μάχες",
  "settings.creditRewards": "Ανταμοιβές",
  "settings.creditRewardsDesc": "Ειδοποίηση για πόντους",
  "settings.friendRequests": "Αιτήματα Φιλίας",
  "settings.friendRequestsDesc": "Ειδοποίηση για φιλίες",
  "settings.sound": "Ηχητικά Εφέ",
  "settings.soundDesc": "Αναπαραγωγή ήχων",
  "settings.email": "Email Ειδοποιήσεις",
  "settings.emailDesc": "Λήψη email",
  "settings.save": "Αποθήκευση",
  "settings.changePassword": "Αλλαγή Κωδικού",
  "settings.changePasswordDesc": "Ενημέρωση κωδικού",
  "settings.newPassword": "Νέος κωδικός (ελάχ. 6)",
  "settings.confirmPassword": "Επιβεβαίωση κωδικού",
  "settings.updatePassword": "Ενημέρωση",
  "settings.updating": "Ενημέρωση...",
  "settings.loggedInAs": "Συνδεδεμένος ως:",
  "settings.language": "Γλώσσα",
  "settings.languageDesc": "Επιλέξτε γλώσσα",
  "login.title": "ΣΎΝΔΕ",
  "login.title2": "ΣΗ",
  "login.subtitle": "Καλώς ήρθες, παίκτη.",
  "login.email": "Email",
  "login.password": "Κωδικός",
  "login.signIn": "Σύνδεση",
  "login.signingIn": "Σύνδεση...",
  "login.forgotPassword": "Ξεχάσατε τον κωδικό;",
  "login.noAccount": "Δεν έχετε λογαριασμό;",
  "login.createAccount": "Δημιουργία Λογαριασμού",
  "login.or": "ή",
  "login.google": "Με Google",
  "login.apple": "Με Apple",
  "signup.title": "ΕΓΓΡΑ",
  "signup.title2": "ΦΗ",
  "signup.subtitle": "Γίνε μέλος. Απόδειξε τη λογική σου.",
  "signup.username": "Όνομα",
  "signup.email": "Email",
  "signup.password": "Κωδικός (ελάχ. 6)",
  "signup.createAccount": "Δημιουργία",
  "signup.creating": "Δημιουργία...",
  "signup.haveAccount": "Έχετε λογαριασμό;",
  "signup.signIn": "Σύνδεση",
  "signup.or": "ή",
  "signup.google": "Με Google",
  "signup.apple": "Με Apple",
  "signup.checkInbox": "ΕΛΕΓΞΤΕ ΤΑ",
  "signup.checkInbox2": "ΕΙΣΕΡΧΟΜΕΝΑ",
  "signup.verifyMsg": "Στείλαμε email στο:",
  "signup.verifyAction": "Πατήστε τον σύνδεσμο στο email.",
  "signup.goLogin": "Σύνδεση",
  "signup.badUsername": "Μη αποδεκτό όνομα.",
  "daily.title": "ΗΜΕΡΗΣΙΑ",
  "daily.title2": "ΠΡΟΚΛΗΣΗ",
  "daily.complete": "ΠΡΟΚΛΗΣΗ",
  "daily.complete2": "ΟΛΟΚΛΗΡΩΘΗΚΕ",
  "daily.dayStreak": "ημερών σειρά",
  "daily.solvedIn": "Έλυσες σε",
  "daily.retryChallenge": "Ξανά",
  "daily.left": "απομένουν",
  "daily.proPerk": "Pro πλεονέκτημα",
  "daily.restartFor": "Επανεκκίνηση",
  "daily.credits": "Πόντοι",
  "daily.discountDay": "Ημέρα έκπτωσης!",
  "daily.retriesUsed": "Εξαντλήθηκαν οι προσπάθειες.",
  "daily.comeBack": "Ελάτε αύριο!",
  "daily.getProRetries": "Pro για προσπάθειες",
  "daily.viewLeaderboard": "Κατάταξη",
  "daily.noPuzzle": "Κανένας γρίφος σήμερα",
  "daily.checkBack": "Ελάτε αύριο!",
  "daily.tasksToday": "Σήμερα έχει",
  "daily.tasks": "εργασίες",
  "daily.wrongPenalty": "Λάθος +5 δευτερόλεπτα. Ο χρόνος μπαίνει στην κατάταξη.",
  "daily.start": "Έναρξη",
  "daily.allComplete": "Όλα ολοκληρώθηκαν!",
  "daily.totalTime": "Συνολικός χρόνος:",
  "daily.penaltyIncl": "Περιλαμβάνει",
  "daily.inPenalties": "ποινές",
  "daily.task": "Εργασία",
  "daily.of": "/",
  "daily.penalties": "ποινές",
  "daily.yourAnswer": "Η απάντησή σου...",
  "daily.wrong5s": "Λάθος! +5 δευτ.",
  "daily.correct": "σωστό! Επόμενο...",
  "daily.creditBonus": "μπόνους πόντων!",
  "practice.title": "ΕΞΑΣΚΗ",
  "practice.title2": "ΣΗ",
  "practice.streak": "Σειρά:",
  "practice.perSolve": "πόντοι ανά λύση",
  "practice.all": "Όλα",
  "practice.correct": "Σωστό!",
  "practice.solvedIn": "Λύθηκε σε",
  "practice.next": "Επόμενος Γρίφος",
  "practice.skip": "Παράλειψη",
  "practice.yourAnswer": "Η απάντησή σου...",
  "practice.wrongTryAgain": "Λάθος! Ξαναπροσπαθήστε.",
  "leaderboard.title": "ΚΑΤΑ",
  "leaderboard.title2": "ΤΑΞΗ",
  "leaderboard.subtitle": "Οι πιο γρήγοροι σήμερα",
  "leaderboard.noOne": "Κανείς δεν έλυσε ακόμα. Γίνε ο πρώτος!",
  "leaderboard.sent": "Εστάλη",
  "shop.title": "ΚΑΤΑΣΤΗΜΑ",
  "shop.credits": "Πόντοι",
  "shop.avatars": "Άβαταρ",
  "shop.proExclusive": "Pro Αποκλειστικά",
  "shop.themes": "Θέματα",
  "shop.titleBadges": "Τίτλοι",
  "shop.buyCredits": "Αγορά Πόντων",
  "shop.equipped": "Εξοπλισμένο",
  "shop.equip": "Εξοπλισμός",
  "shop.buy": "Αγορά",
  "shop.owned": "Ιδιοκτησία",
  "shop.active": "Ενεργό",
  "shop.apply": "Εφαρμογή",
  "shop.purchase": "Αγορά",
  "shop.getPro": "Pro",
  "shop.earnDaily": "Κέρδισε",
  "shop.earnDailyCredits": "πόντους",
  "shop.forEveryDaily": "για κάθε ημερήσια πρόκληση",
  "shop.upgradeProShop": "Pro για αποκλειστικά & 2× πόντους",
  "shop.themeApplied": "Θέμα εφαρμόστηκε!",
  "friends.title": "ΦΙ",
  "friends.title2": "ΛΟΙ",
  "friends.searchPlaceholder": "Αναζήτηση...",
  "friends.alreadyConnected": "Ήδη συνδεδεμένοι",
  "friends.add": "Προσθήκη",
  "friends.friends": "Φίλοι",
  "friends.requests": "Αιτήματα",
  "friends.noFriends": "Χωρίς φίλους ακόμα. Αναζήτηση παικτών!",
  "friends.incoming": "Εισερχόμενα",
  "friends.accept": "Αποδοχή",
  "friends.sent": "Εστάλη",
  "friends.pending": "Αναμονή...",
  "friends.noRequests": "Κανένα αίτημα.",
  "friends.requestSent": "Αίτημα εστάλη!",
  "friends.alreadySent": "Ήδη εστάλη!",
  "friends.failed": "Αποτυχία",
  "friends.added": "Φίλος προστέθηκε!",
  "friends.declined": "Αίτημα απορρίφθηκε",
  "general.loading": "Φόρτωση...",
  "general.error": "Σφάλμα",
  "general.success": "Επιτυχία",
  "general.cancel": "Ακύρωση",
  "general.save": "Αποθήκευση",
  "general.delete": "Διαγραφή",
  "general.back": "Πίσω",
  "general.next": "Επόμενο",
  "general.submit": "Υποβολή",
  "general.search": "Αναζήτηση...",
  "general.welcomeBack": "Καλώς ήρθες!",
  "general.2xPro": "2× Pro",
  "general.2xEarn": "2× ΚΕΡΔΗ",
};

const zh: Record<string, string> = {
  "nav.home": "首页",
  "nav.leaderboard": "排行榜",
  "nav.practice": "练习",
  "nav.shop": "商店",
  "nav.friends": "好友",
  "nav.lobbies": "大厅",
  "nav.community": "社区",
  "nav.profile": "个人资料",
  "nav.login": "登录",
  "nav.settings": "设置",
  "hero.title": "Logic",
  "hero.title2": "Guesser",
  "hero.subtitle": "用每日谜题测试你的脑力，与朋友对战，攀登全球排行榜。",
  "hero.daily": "开始每日挑战",
  "hero.practice": "练习模式",
  "hero.badge": "新的每日挑战",
  "hero.statPuzzles": "已解谜题",
  "hero.statPlayers": "活跃玩家",
  "hero.statDaily": "每日挑战",
  "profile.level": "等级",
  "profile.streak": "连胜",
  "profile.solved": "已解决",
  "profile.credits": "积分",
  "profile.logout": "退出",
  "profile.editBio": "编辑简介",
  "profile.addBio": "添加简介",
  "profile.noBio": "暂无简介",
  "profile.editName": "修改名字",
  "profile.upgradePro": "升级到Pro",
  "profile.goPro": "Pro",
  "profile.changeName": "更改用户名",
  "profile.saveName": "保存",
  "settings.title": "设置",
  "settings.notifications": "通知",
  "settings.notificationsDesc": "启用通知",
  "settings.battleInvites": "对战邀请",
  "settings.battleInvitesDesc": "对战邀请通知",
  "settings.creditRewards": "积分奖励",
  "settings.creditRewardsDesc": "积分通知",
  "settings.friendRequests": "好友请求",
  "settings.friendRequestsDesc": "好友请求通知",
  "settings.sound": "音效",
  "settings.soundDesc": "游戏音效",
  "settings.email": "邮件通知",
  "settings.emailDesc": "接收邮件提醒",
  "settings.save": "保存设置",
  "settings.changePassword": "修改密码",
  "settings.changePasswordDesc": "更新密码",
  "settings.newPassword": "新密码（至少6位）",
  "settings.confirmPassword": "确认密码",
  "settings.updatePassword": "更新密码",
  "settings.updating": "更新中...",
  "settings.loggedInAs": "登录为：",
  "settings.language": "语言",
  "settings.languageDesc": "选择语言",
  "login.title": "登",
  "login.title2": "录",
  "login.subtitle": "欢迎回来，挑战者。",
  "login.email": "邮箱",
  "login.password": "密码",
  "login.signIn": "登录",
  "login.signingIn": "登录中...",
  "login.forgotPassword": "忘记密码？",
  "login.noAccount": "没有账户？",
  "login.createAccount": "创建账户",
  "login.or": "或",
  "login.google": "使用Google",
  "login.apple": "使用Apple",
  "signup.title": "注",
  "signup.title2": "册",
  "signup.subtitle": "加入挑战，展示逻辑。",
  "signup.username": "用户名",
  "signup.email": "邮箱",
  "signup.password": "密码（至少6位）",
  "signup.createAccount": "创建账户",
  "signup.creating": "创建中...",
  "signup.haveAccount": "已有账户？",
  "signup.signIn": "登录",
  "signup.or": "或",
  "signup.google": "使用Google",
  "signup.apple": "使用Apple",
  "signup.checkInbox": "查看",
  "signup.checkInbox2": "邮箱",
  "signup.verifyMsg": "验证邮件已发送至：",
  "signup.verifyAction": "点击邮件中的链接验证账户。",
  "signup.goLogin": "去登录",
  "signup.badUsername": "用户名包含不当语言。",
  "daily.title": "每日",
  "daily.title2": "挑战",
  "daily.complete": "挑战",
  "daily.complete2": "完成",
  "daily.dayStreak": "天连胜",
  "daily.solvedIn": "今天的挑战完成时间：",
  "daily.retryChallenge": "重试",
  "daily.left": "剩余",
  "daily.proPerk": "Pro特权",
  "daily.restartFor": "重新开始",
  "daily.credits": "积分",
  "daily.discountDay": "折扣日！",
  "daily.retriesUsed": "今天的重试已用完。",
  "daily.comeBack": "明天再来！",
  "daily.getProRetries": "获取Pro来重试",
  "daily.viewLeaderboard": "查看排行榜",
  "daily.noPuzzle": "今天没有谜题",
  "daily.checkBack": "明天再来！",
  "daily.tasksToday": "今天的挑战有",
  "daily.tasks": "道题",
  "daily.wrongPenalty": "错误答案+5秒。总时间计入排行榜。",
  "daily.start": "开始挑战",
  "daily.allComplete": "全部完成！",
  "daily.totalTime": "总时间：",
  "daily.penaltyIncl": "包含",
  "daily.inPenalties": "秒罚时",
  "daily.task": "题目",
  "daily.of": "/",
  "daily.penalties": "秒罚时",
  "daily.yourAnswer": "你的答案...",
  "daily.wrong5s": "错误！+5秒罚时",
  "daily.correct": "正确！下一题...",
  "daily.creditBonus": "积分奖励！",
  "practice.title": "练习",
  "practice.title2": "模式",
  "practice.streak": "连胜：",
  "practice.perSolve": "积分/题",
  "practice.all": "全部",
  "practice.correct": "正确！",
  "practice.solvedIn": "用时",
  "practice.next": "下一题",
  "practice.skip": "跳过",
  "practice.yourAnswer": "你的答案...",
  "practice.wrongTryAgain": "错误！再试一次。",
  "leaderboard.title": "排行",
  "leaderboard.title2": "榜",
  "leaderboard.subtitle": "今日最快",
  "leaderboard.noOne": "今天还没人完成挑战。成为第一个！",
  "leaderboard.sent": "已发送",
  "shop.title": "商店",
  "shop.credits": "积分",
  "shop.avatars": "头像",
  "shop.proExclusive": "Pro专属",
  "shop.themes": "主题",
  "shop.titleBadges": "称号",
  "shop.buyCredits": "购买积分",
  "shop.equipped": "已装备",
  "shop.equip": "装备",
  "shop.buy": "购买",
  "shop.owned": "已拥有",
  "shop.active": "使用中",
  "shop.apply": "应用",
  "shop.purchase": "购买",
  "shop.getPro": "获取Pro",
  "shop.earnDaily": "每次每日挑战获得",
  "shop.earnDailyCredits": "积分",
  "shop.forEveryDaily": "",
  "shop.upgradeProShop": "升级Pro获得专属头像和2×积分",
  "shop.themeApplied": "主题已应用！",
  "friends.title": "好",
  "friends.title2": "友",
  "friends.searchPlaceholder": "搜索用户名...",
  "friends.alreadyConnected": "已是好友",
  "friends.add": "添加",
  "friends.friends": "好友",
  "friends.requests": "请求",
  "friends.noFriends": "还没有好友。搜索玩家吧！",
  "friends.incoming": "收到的",
  "friends.accept": "接受",
  "friends.sent": "已发送",
  "friends.pending": "等待中...",
  "friends.noRequests": "没有待处理的请求。",
  "friends.requestSent": "好友请求已发送！",
  "friends.alreadySent": "请求已发送！",
  "friends.failed": "发送失败",
  "friends.added": "好友已添加！",
  "friends.declined": "请求已拒绝",
  "general.loading": "加载中...",
  "general.error": "错误",
  "general.success": "成功",
  "general.cancel": "取消",
  "general.save": "保存",
  "general.delete": "删除",
  "general.back": "返回",
  "general.next": "下一步",
  "general.submit": "提交",
  "general.search": "搜索...",
  "general.welcomeBack": "欢迎回来！",
  "general.2xPro": "2× Pro",
  "general.2xEarn": "2× 收益",
};

const translations: Record<Language, Record<string, string>> = { en, hu, la, el, zh };

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType>({
  language: "en",
  setLanguage: () => {},
  t: (key) => key,
});

export const useLanguage = () => useContext(LanguageContext);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem("logicguesser-lang");
    return (saved as Language) || "en";
  });

  const setLanguage = useCallback((lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem("logicguesser-lang", lang);
  }, []);

  const t = useCallback((key: string) => {
    return translations[language]?.[key] || translations.en[key] || key;
  }, [language]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}
